app <- ShinyDriver$new("../../", seed = 123)
app$snapshotInit("mytest", screenshot = FALSE)

app$snapshot()
app$setInputs(email_address = "test")
app$setInputs(domain = "Professional")
app$setInputs(last_phone = "Less than 6 months ago")
app$setInputs(xai = "Professional")
app$setInputs(`Click.Counter` = "click")
app$snapshot()
app$setInputs(`nd_Question-ndnd1` = "brand")
app$setInputs(`nd_Question-ndnd1` = c("brand", "back_camera_mpix"))
app$setInputs(`nd_Question-ndnd1` = c("brand", "back_camera_mpix", "front_camera_mpix"))
app$setInputs(`nd_Question-submit` = "click")
app$snapshot()
app$setInputs(`Click.Counter` = "click")
app$snapshot()
app$setInputs(`st_Question-submit` = "click", wait_=FALSE, values_=FALSE)
app$snapshot()
