app <- ShinyDriver$new("../../", seed = 123)
app$snapshotInit("mytest2", screenshot = FALSE)

app$snapshot()
app$setInputs(email_address = "te")
app$setInputs(email_address = "test")
app$setInputs(domain = "Fundamental")
app$setInputs(last_phone = "Less than 6 months ago")
app$setInputs(xai = "Fundamental")
app$setInputs(`Click.Counter` = "click")
app$snapshot()
app$snapshot()
app$setInputs(`nd_Question-ndnd1` = "brand")
app$setInputs(`nd_Question-ndnd1` = c("brand", "back_camera_mpix"))
app$setInputs(`nd_Question-ndnd1` = c("brand", "back_camera_mpix", "front_camera_mpix"))
app$setInputs(`nd_Question-submit` = "click")
app$snapshot()
app$setInputs(`Click.Counter` = "click")
app$snapshot()
app$setInputs(`Click.Counter` = "click")
app$snapshot()
app$setInputs(`rd_Question-rd_1_7` = "Highly increases")
app$setInputs(`rd_Question-rd_2_7` = "Highly increases")
app$setInputs(`rd_Question-rd_3_7` = "Highly increases")
app$setInputs(`rd_Question-rd_3_8` = "Slightly increases")
app$setInputs(`rd_Question-rd_4_8` = "Slightly increases")
app$snapshot()
app$setInputs(`rd_Question-submit` = "click")
app$snapshot()
